# Generated by Django 5.2.8 on 2025-12-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0002_customuser_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ampu_mapel',
            field=models.ManyToManyField(blank=True, help_text='Mata pelajaran yang diampu (khusus Guru)', related_name='guru_set', to='academic.matapelajaran'),
        ),
    ]
