# Generated by Django 4.2.7 on 2026-01-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_ampu_mapel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Password in plain text (generated automatically)', max_length=128, null=True),
        ),
    ]
