# Generated by Django 4.2.7 on 2026-01-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ampu_mapel',
            field=models.ManyToManyField(blank=True, to='academic.matapelajaran'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.kelas'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Untuk keperluan debug/recovery (Not Secure)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin Sekolah'), ('guru', 'Guru'), ('siswa', 'Siswa'), ('waka', 'Waka Kurikulum')], default='siswa', max_length=10),
        ),
    ]
