# Generated by Django 4.2.7 on 2026-01-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0006_alter_customuser_ampu_mapel_alter_customuser_kelas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ampu_mapel',
            field=models.ManyToManyField(blank=True, help_text='Mata pelajaran yang diampu (khusus Guru)', related_name='guru_set', to='academic.matapelajaran'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa_set', to='academic.kelas'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Password in plain text (generated automatically)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('guru', 'Guru'), ('siswa', 'Siswa'), ('proktor', 'Proktor/Panitia'), ('waka', 'Waka Kurikulum')], default='siswa', max_length=10),
        ),
    ]
