# Generated by Django 4.2.7 on 2026-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_ampu_mapel_alter_customuser_kelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nama',
            field=models.CharField(default='', max_length=255, verbose_name='Nama Lengkap'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nisn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NISN (Siswa)'),
        ),
    ]
