# Generated by Django 4.2.7 on 2026-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='tingkat',
            field=models.IntegerField(default=10, help_text='10, 11, 12'),
        ),
    ]
