# Generated by Django 5.2.8 on 2025-12-02 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(limit_choices_to={'role': 'guru'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.matapelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='ButirSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='soal_images/')),
                ('opsi_a', models.TextField()),
                ('opsi_b', models.TextField()),
                ('opsi_c', models.TextField()),
                ('opsi_d', models.TextField()),
                ('opsi_e', models.TextField()),
                ('kunci_jawaban', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('bobot', models.IntegerField(default=1)),
                ('bank_soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.banksoal')),
            ],
        ),
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ujian', models.CharField(max_length=200)),
                ('waktu_mulai', models.DateTimeField()),
                ('durasi', models.IntegerField(help_text='Durasi dalam menit')),
                ('token', models.CharField(max_length=6)),
                ('aktif', models.BooleanField(default=False)),
                ('bank_soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.banksoal')),
                ('kelas', models.ManyToManyField(to='academic.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='SesiUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.DateTimeField(auto_now_add=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('siswa', models.ForeignKey(limit_choices_to={'role': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.ujian')),
            ],
        ),
        migrations.CreateModel(
            name='JawabanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(blank=True, max_length=1, null=True)),
                ('ragu_ragu', models.BooleanField(default=False)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.butirsoal')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_siswa', to='exams.sesiujian')),
            ],
            options={
                'unique_together': {('sesi', 'soal')},
            },
        ),
    ]
