# Generated by Django 5.2.8 on 2025-12-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiujian',
            name='nilai',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ujian',
            name='token',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
