# Generated by Django 4.2.27 on 2025-12-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_sesiujian_nilai_alter_ujian_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='semester',
            field=models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=10),
        ),
    ]
