# Generated by Django 4.2.27 on 2025-12-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_ujian_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butirsoal',
            name='opsi_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='butirsoal',
            name='opsi_e',
            field=models.TextField(blank=True, null=True),
        ),
    ]
