# Generated by Django 4.2.7 on 2026-01-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_butirsoal_opsi_d_alter_butirsoal_opsi_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='butirsoal',
            name='jenis_soal',
            field=models.CharField(choices=[('PG', 'Pilihan Ganda'), ('ESSAY', 'Essay / Uraian')], default='PG', max_length=10),
        ),
        migrations.AddField(
            model_name='jawabansiswa',
            name='jawaban_essay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabansiswa',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiujian',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Mengerjakan'), ('WAITING_GRADE', 'Menunggu Koreksi'), ('GRADED', 'Selesai Dinilai')], default='ONGOING', max_length=20),
        ),
        migrations.AlterField(
            model_name='butirsoal',
            name='kunci_jawaban',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='butirsoal',
            name='opsi_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='butirsoal',
            name='opsi_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='butirsoal',
            name='opsi_c',
            field=models.TextField(blank=True, null=True),
        ),
    ]
