# Generated by Django 4.2.7 on 2026-01-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_butirsoal_jenis_soal_jawabansiswa_jawaban_essay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butirsoal',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='soal_audio/'),
        ),
    ]
