# Generated by Django 4.2.7 on 2026-01-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_butirsoal_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksoal',
            name='kode',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
