# Generated by Django 4.2.7 on 2026-01-23 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0007_banksoal_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalPengawas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.kelas')),
                ('proktor', models.ForeignKey(limit_choices_to={'role': 'proktor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_pengawas', to='exams.ujian')),
            ],
            options={
                'unique_together': {('ujian', 'kelas')},
            },
        ),
    ]
