# Generated by Django 4.2.7 on 2026-01-23 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0008_sesiujian_score_sesiujian_sisa_waktu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalpengawas',
            name='proktor',
            field=models.ForeignKey(limit_choices_to={'role': 'guru'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
