# Generated by Django 4.2.7 on 2026-01-30 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_sesiujian_score_sesiujian_sisa_waktu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiujian',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiujian',
            name='sisa_waktu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jawabansiswa',
            name='jawaban',
            field=models.CharField(blank=True, db_column='jawaban_dipilih', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='jawabansiswa',
            name='sesi',
            field=models.ForeignKey(db_column='sesi_ujian_id', on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_siswa', to='exams.sesiujian'),
        ),
        migrations.AlterField(
            model_name='jawabansiswa',
            name='soal',
            field=models.ForeignKey(db_column='butir_soal_id', on_delete=django.db.models.deletion.CASCADE, to='exams.butirsoal'),
        ),
    ]
